### ISSUE TITLE
Count the cyclomatic complexity of large functions of the code 

### ISSUE THREAD

**Issue by NilsLofberg** [yamean3567/Algorithms#4]
Exclude third-party code and generated code in this. If
you have a tool, list ten (10) functions or methods with high complexity. In addition to that (or if you have
no tool), count the cyclomatic complexity of five complex functions by hand, either by choosing five out of
the ten functions shown by the tool, or, if no tool was available, five functions that appear to be complex.
Note: This document assumes your group has five members; if your group is smaller, total numbers scale
with the group size: 8 functions with four active group members, or six with three active members.
Note: Use at least two group members to count the complexity separately, to get a reliable results. Use a
third member if the two counts differ.
1. What are your results? Did everyone get the same result? Is there something that is unclear? If you
have a tool, is its result the same as yours?
2
2. Are the functions/methods with high CC also very long in terms of LOC?
3. What is the purpose of these functions? Is it related to the high CC?
4. If your programming language uses exceptions: Are they taken into account by the tool? If you think
of an exception as another possible branch (to the catch block or the end of the function), how is the
CC affected?
5. Is the documentation of the function clear about the different possible outcomes induced by different
branches taken?

**Comment by lollanlollan** [comment]
Suggestions for the five functions from the list of 11 most complex functions:
Function nr 3, getTreeDisplay in TreePrinter. Branch coverage 0%. CNN 27.
Function nr 4, GenericSegmentTree in GenericSegmentTree. Branch coverage 56%, CNN 24. 
Function nr 7, lineSegmentLineSegmentIntersection in LineSegmentLineSegmentIntersection. Branch coverage 0%, CNN 20.
Function nr 10, construct in LongestCommonPrefixArray. Branch coverage 0%, CNN 17.
Function nr 11, construct in LongestRepeatedSubstring. Branch coverage 0%, CNN 17.
